version: "3.8"

services:
  hlds-manager:
    restart: always
    image: af0x/hlds-agent:monitoring
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EXTERNAL_IP: ${EXTERNAL_IP}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_RECONNECT_TIMEOUT_SEC: 10
    volumes:
      - ./docker/data:/app/data

  fast-download:
    restart: always
    image: af0x/rehlds-fastdl
    ports:
      - "2750:2750"
    volumes:
      - ./resources:/static
  cs:
    restart: always
    profiles:
      - all
      - cs
    image: af0x/hlds-agent:cs-nosteam
    environment:
      RCON_PASSWORD: ${RCON_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PORT: 27015
      GRPC_API_PORT: 8090
      MAP: de_dust2_2x2
      GAME_TYPE: cs-classic
    volumes:
      - ./docker/cs/maps.ini:/hlds/cstrike/addons/amxmodx/configs/maps.ini
      - ./docker/cs/server.cfg:/hlds/cstrike/server.cfg
      - ./docker/cs/maps:/hlds/cstrike/maps
      - ./docker/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 512M
    expose:
      - "27015/tcp"
      - "27015/udp"
      - "8090"
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
  csdm:
    restart: always
    profiles:
      - all
      - csdm
    image: af0x/hlds-agent:csdm-nosteam
    environment:
      RCON_PASSWORD: ${RCON_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PORT: 27017
      GRPC_API_PORT: 8090
      MAP: de_dust2_2x2
      GAME_TYPE: cs-dm
    volumes:
      - ./docker/csdm/maps.ini:/hlds/cstrike/addons/amxmodx/configs/maps.ini
      - ./docker/csdm/server.cfg:/hlds/cstrike/server.cfg
      - ./docker/csdm/maps:/hlds/cstrike/maps
      - ./docker/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 512M
    expose:
      - "27017/tcp"
      - "27017/udp"
      - "8090"
    ports:
      - "27017:27017/tcp"
      - "27017:27017/udp"
  half-life:
    restart: always
    profiles:
      - all
      - hl
    image: af0x/hlds-agent:hl-nosteam
    environment:
      RCON_PASSWORD: ${RCON_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PORT: 27016
      GRPC_API_PORT: 8090
      MAP: 1337_Street
      GAME_TYPE: half-life

    volumes:
      - ./docker/half-life/maps.ini:/hlds/valve/addons/amxmodx/configs/maps.ini
      - ./docker/half-life/server.cfg:/hlds/valve/server.cfg
      - ./docker/half-life/maps:/hlds/valve/maps
      - ./docker/users.ini:/hlds/valve/addons/amxmodx/configs/users.ini
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 512M
    expose:
      - "27016/tcp"
      - "27016/udp"
      - "8090"
    ports:
      - "27016:27016/tcp"
      - "27016:27016/udp"
networks:
  default:
    external: true
    name: algol-net
